### ISSUE TITLE
Enable to get schema and catalog information from table

### ISSUE THREAD

**Issue by Rachelint** [CeresDB/horaedb#1157]
### Describe This Problem

We ofen need to know table's schema and catalog information, and we can do it just by passing from caller now...
It make the codes verbose and messy...

### Proposal

Store `schema id`,  `catalog manager` in `TableData`.

**Comment by dust1** [comment]
If I want to finish this issue, is it directly assigned to myself?

**Comment by Rachelint** [comment]
> If I want to finish this issue, is it directly assigned to myself?

Yes, welcome!
