### ISSUE TITLE
Faster to drop table

### ISSUE THREAD

**Issue by ShiKaiWi** [CeresDB/horaedb#1309]
### Describe This Problem

It's slow to drop a table because flush must be done before real drop.

### Proposal

Actually, there is no need to flush memtable before dropping, and just dropping the memtable may make the dropping table faster.

**Comment by jiacai2050** [comment]
This issue has been resolved in https://github.com/CeresDB/horaedb/pull/1257, do you still see flush happens when drop table?

**Comment by ShiKaiWi** [comment]
> This issue has been resolved in #1257, do you still see flush happens when drop table?

Umm... I guess the deployed ceresdb-server may be outdated.
