### ISSUE TITLE
build ERROR

### ISSUE THREAD

**Issue by tematou** [CeresDB/horaedb#1350]
### Describe this problem

error: failed to run custom build command for `generated_types v0.1.0 (https://github.com/CeresDB/influxql.git?rev=acbd3ad7651f2deb74857155bea892f88926da57#acbd3ad7)`

### Server version

da7c5a126949fc385fd78e57e4f2ce3fb3d19c2f

### Steps to reproduce

cargo build --release

**Comment by tematou** [comment]
please solve this problem
![screenshot-20231207-113556](https://github.com/CeresDB/horaedb/assets/35472988/d5b212a9-966c-4df9-b967-857e9005623b)

**Comment by jiacai2050** [comment]
It seems you haven't installed protobuf-compiler?

**Comment by tematou** [comment]
Yes,thank you!



---- Replied Message ----
| From | Jiacai ***@***.***> |
| Date | 12/07/2023 11:40 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [CeresDB/horaedb] build ERROR (Issue #1350) |

It seems you haven't installed protobuf-compiler?

**Comment by jiacai2050** [comment]
Closing, feel free to open new issue if you still have questions.
