### ISSUE TITLE
gg

### ISSUE THREAD

**Issue by tematou** [CeresDB/horaedb#1361]
### Describe This Problem

能出个正经的文档吗，官网和github完全不一样？
![image](https://github.com/CeresDB/horaedb/assets/35472988/83199b19-5ec1-44bd-8b02-02cad8d4fa3e)
![image](https://github.com/CeresDB/horaedb/assets/35472988/8bddf92e-a5f2-42b1-bffa-758e159d9380)

### Proposal

真的依托答辩。。。

**Comment by ZuLiangWang** [comment]
Please refer to the document link in Github. The official website document below is not the document of the CeresDB open source version, it is the document of the CeresDB commercial version.

请参照 Github 中的文档链接，下面的官网文档并非 CeresDB 开源版本的文档，它是 CeresDB 商业版的文档。
