### ISSUE TITLE
Add integration test for alter table options

### ISSUE THREAD

**Issue by jiacai2050** [CeresDB/horaedb#953]
### Describe This Problem

Related with https://github.com/CeresDB/docs/pull/82

### Proposal

- https://github.com/CeresDB/ceresdb/blob/5ea6c0f3b87011d2e6802c9bb27916f853084a08/integration_tests/cases/env/cluster/ddl/alter_table.sql#L1

**Comment by jiacai2050** [comment]
Thanks, assigned.

**Comment by caicancai** [comment]
> Thanks, assigned.

Thank you for assigning this pr to me, I would like to ask if there is such a specification or reference

**Comment by jiacai2050** [comment]
Already described above. See https://github.com/CeresDB/docs/pull/82

**Comment by caicancai** [comment]
> Already described above. See [CeresDB/docs#82](https://github.com/CeresDB/docs/pull/82)

So I just need to add test to alter_table.sql? I thought I needed to write test code from scratch

**Comment by caicancai** [comment]
According to my testing process,

```sql
-- create a table and add a column to it
CREATE TABLE `t`(a int, t timestamp NOT NULL, TIMESTAMP KEY(t)) ENGINE = Analytic;
ALTER TABLE `t` MODIFY SETTING write_buffer_size='300M';
``` 
column name cannot be tsid
